### ISSUE TITLE
can add the compose of times?

### ISSUE THREAD

**Issue by datalee** [RamiKrispin/TSstudio#1]
like the function of stats:
`AirPassengerscomponents <- decompose(AirPassengers)`
`plot(AirPassengerscomponents)`
[https://github.com/datalee/decompose-png/blob/master/Rplot.png](url)

**Comment by RamiKrispin** [comment]
Yes! defiantly on my to-do list

**Comment by RamiKrispin** [comment]
The decompose function is now available on the development version on github, please use:
`devtools::install_github("RamiKrispin/TSstudio")`
`library(TSstudio)`
`decompose_ly(AirPassengers)`
