### ISSUE TITLE
plot_forecast dates x-axis wrong format

### ISSUE THREAD

**Issue by verajosemanuel** [RamiKrispin/TSstudio#10]
When plotting a forecast dates are shown as fractions or numerical amounts. I dont get really the proper correspondence with real dates.

This is a capture from a time series starting in JUNE. As you can see figures are confusing. (June is not 2107.45 on my mind)

![CA](https://user-images.githubusercontent.com/15836677/55234657-efb1f780-522b-11e9-8aa0-425e25a1a0a0.PNG)

`plot_forecast(fcast_arima, title = "ARIMA Forecast Plot")`

**Comment by RamiKrispin** [comment]
Yes, you are right, apparently, there is a discrepancy between the output of the `time` function and its numeric values. So if you run this:
`USgas %>% tail(12) %>% time()` it will be lagged when turn to numeric values:
`USgas %>% tail(12) %>% time() %>% as.numeric()`. I pushed an [update](https://github.com/RamiKrispin/TSstudio/commit/d39c978c5a761aeb6ba46986fc9de41a161ab9be) for the dev version, will be available on CRAN on the next release.

Thanks for the observation!
