### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sbasyrine** [RamiKrispin/TSstudio#20]
Hello! I'm a master student and I'm working on predicting and forecasting the status of Ireland's charging stations given a time series dataset. What I need to do is to predict the status of  exactly three charging stations at a particular hour or period of time in the future (for example what would be the state of the charging station tomorrow at 8:00 am?)
If you could help me, it will mean a lot to me and I'll be so grateful.
Sincerely.

**Comment by RamiKrispin** [comment]
Hello,

There is so many ways to do it, but a simple one, assuming:
* The data is regular time series data (e.g., equally spaced)
* You have enough historical data 
* Each charging station is a series by itself

Then, I would consider the following steps:
* correlation and seasonal analysis to understand the structure of the series and patterns or insights
* Use those insights about the series to create new futures (seasonal components, special events, holidays, outlier, etc.)
* Build a time series model to forecast the future event

As your data is hourly, I would expect that you will have multiple seasonality (e.g., day of the week, the month of the year, etc.), so you should think about an approach to handle it.

Hope that makes sense.

On a side note, this forum is designed to rais specific issues related to the package code (e..g, error, bug fixing, etc.)...

Best,
Rami
