### ISSUE TITLE
nnetar error in train_model function

### ISSUE THREAD

**Issue by VitoFanelli** [RamiKrispin/TSstudio#47]
train_model function always returns the same error "Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),: 'data' must be of a vector type, was 'NULL'" when "nnetar" type model is setted.

The file below conteins an example.

[nnetar_problem_tsstudio.txt](https://github.com/RamiKrispin/TSstudio/files/4076083/nnetar_problem_tsstudio.txt)

**Comment by RamiKrispin** [comment]
Hi @VitoFanelli  this error was fixed and available on the dev version, will push it in the coming days to CRAN
