### ISSUE TITLE
horizon parameter doesn't work

### ISSUE THREAD

**Issue by VitoFanelli** [RamiKrispin/TSstudio#48]
horizon parameter is ignored. Best model forecast missing. Maybe the problem is here

 # Creating grid of all the modeling combinations
  grid_df <- base::expand.grid(models_df$model_id, s1, train_method$sample.out, stringsAsFactors = FALSE) %>% 
    stats::setNames(c("model_id", "start", "horizon")) %>% ...

sample.out is overwrite with "horizon"?

**Comment by RamiKrispin** [comment]
Hi @VitoFanelli, 

Could you please provide a reproducible example (how did you generate `model_df` object)? I am struggling to understand what is `models_df` object

**Comment by RamiKrispin** [comment]
The issue was on the `train_model` function - fixed and updated on version 0.1.6
