### ISSUE TITLE
plot = FALSE / TRUE

### ISSUE THREAD

**Issue by joaopedrodominguesufes** [RamiKrispin/TSstudio#5]
Hello Rami,

I'm using your function "ts_backtesting" to know the best forcast model, so once I already know wich model I and to use, I`m trying to run only the forecast without the plot. But when I change the Logical arguments , if TRUE desplay a plot with the backtesting progress, I put plot = FALSE, it still showing me the plot. Could you help me with this issue, please?

I`m using the code below to run a loop for few time series at once, so if I see the plot for every time serie it become too slow:

Result.previ = matrix(NA,nrow=6,ncol=0)
Result.previ =data.frame(Result.previ) 

j=0
repeat{
  y <- Data.cut[,(j+1)] 
  demand <- ts(y, start = c(1, 1), frequency = 6)
  test.forcast <- ts_backtesting(demand, window_size = 6, h = 6, periods = 6, error = "RMSE", models = "a", plot = FALSE)
  previ <- as.data.frame(test.forcast$leadForecast$mean)
  
  colnames(previ) <- names[j+1,1]
  
  Result.previ = cbind(Result.previ,previ)
  
  j=j+1
  if (j >= ncol(Data.all)) break()
}

Really appreciate your attention

**Comment by RamiKrispin** [comment]
Hi @joaopedrodominguesufes, thank you for the feedback I pushed an update. The function now should not plot the output when the  `plot` argument is equal to `FALSE`

**Comment by joaopedrodominguesufes** [comment]
It worked well now. This package is helping me a lot, great work

**Comment by joaopedrodominguesufes** [comment]
It worked well now. This package is helping me a lot, great work

By chance, do you work with forecast using regression LASSO in the package glmnet or HDeconometrics?

**Comment by RamiKrispin** [comment]
Great! BTW the output of the function contains all the forecasts, you don't need to rerun it again.

I didn't use LASSO for forecasting.
