### ISSUE TITLE
 could not find function "ts_backtesting"

### ISSUE THREAD

**Issue by rczen** [RamiKrispin/TSstudio#56]
Hi,

I am following along your excellent book.
When running the following code:

```
set.seed(1234)

ts_forecast <- ts_backtesting(
  ts.obj = ts,
  periods = 6,
  models = "abehntw",
  error = "MAPE",
  window_size = 6,
  h = 60,
  plot=FALSE)

```
I am getting an error that the function "ts_backtesting" could not be found.
Any idea what is wrong.

Thank you.

**Comment by RamiKrispin** [comment]
Hi @rczen,

Thanks for the feedback. The `ts_backtesting` was deprecated and on version 0.1.5 and defunct by the [train_model](https://ramikrispin.github.io/TSstudio/articles/forecasting.html#training-multiple-time-series-model-with-backtesting)  function, which provides the same functionality but more flexible. As many people contact me about the `ts_backtesting`, the plan is to return the function on the next release of the package.

In the meanwhile, until the next update to CRAN, you can install version 0.1.5 from CRAN archive using:
```
utils::install.packages("https://cran.r-project.org/src/contrib/Archive/TSstudio/TSstudio_0.1.5.tar.gz", repos=NULL, type = "source")
```

Let me know if you have any issues with that.

**Comment by rczen** [comment]
Hi Rami,

Thanks for the prompt reply.

I used the train_model function, and got a warning about possible convergence problem.
Attached is the analysis report, that show the warning. 

[ts.pdf](https://github.com/RamiKrispin/TSstudio/files/5341067/ts.pdf)

It is not clear which models had a convergence problem.
Secondly how the problem cab be resolved, and does it impact the reliability of the MAPE.

Thanks for your help, 
I love  the book and the package.

Ronen

**Comment by RamiKrispin** [comment]
Hi Ronen,

Unfortunately, as the function is based on `lapply` to run the models, and in the current setting it "split" all the warnings after it finishes to run the models. Currently, the only way to match the warning to the model is to run one model at a time. I opened an issue (#57)  to had this functionality for the next release. 

Thanks for the feedback!
Rami

**Comment by rczen** [comment]
Hi Rami,

I see, thanks for the reply.

What does it mean that the model did not converge.

Thanks,

Ronen

**Comment by RamiKrispin** [comment]
I believe that the converge message is related to optimization mechanism of the ARIMA model. Essentially, the optimization mechanism runs for n iteration, and stop if the optimization algorithm converge to the optimal point, and further iteration won't provide significant improvement. So, your warning just saying that for the default setting of iteration the optimization algorithm did not coverage to the optimal point and, potentially, there is room for additional improvement. 

You can try to increase the number of iterations by adding this argument - `list(maxit = 1000)` (I think by default it is set to 500).

The `auto.arima` is a warper on top of the **stats** package `arima` function. This function (`arima`) uses different methods to optimize the model coefficients with the `method` (which defines the method to apply) and `optim.control = list()` argument that defines the optimization parameters.  The function that actually running the optimization is [optim](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/optim). The `control = list()` is defining the number of iterations.

**Comment by RamiKrispin** [comment]
I see that also `HoltWinters` use the `optim.control` so the warning could come from this model

**Comment by rczen** [comment]
Thank you Rami.
