### ISSUE TITLE
Visualization results of "check_res" is missing

### ISSUE THREAD

**Issue by yingpublic** [RamiKrispin/TSstudio#59]
Hi, Thank you for building this package! It's useful for my time series learning path. I'd like to use one of the function "check_res" to visualize the time series fitting results. However, it seems like the code won't plot for me. I am pasting one of the code I found online which use the build-in dataset. Do I need to write extra code to plot the results?

data(USgas)

#### Create a model
fit <- auto.arima(USgas)

#### Check the residuals of the model
check_res(fit)

**Comment by RamiKrispin** [comment]
Hi @yingpublic 

Did you load the packages? could you please try the following code and let me know if it is working or not:

```
library(forecast)
library(TSstudio)
data("USgas")

fit <- auto.arima(USgas)
check_res(fit)
```

This is the expected output:
![image](https://user-images.githubusercontent.com/12760966/115659353-4ac15600-a2ef-11eb-80c1-877bff446a6a.png)

**Comment by yingpublic** [comment]
Yes, I load the package before using it. There is no error message but there is no plot as well. I just want to mention that I use google colab with RMagic to run my code (due to large dataset saved in google drive). 

%load_ext rpy2.ipython
%%R
library(forecast)
library(TSstudio)
data("USgas")
fit <- auto.arima(USgas)
check_res(fit)

**Comment by RamiKrispin** [comment]
It could be the colab/RMagic do not support (or you are missing components) for plotting d3 based vis. Can you try the following:

```
library(plotly)

fig <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)

fig
```
You should expect this:
![image](https://user-images.githubusercontent.com/12760966/115798398-071c2a00-a38b-11eb-8960-51629c918815.png)
