### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [RamiKrispin/TSstudio#63]
Hi.

This is a friendly reminder that [`plan(multiprocess)`](https://future.futureverse.org/reference/multiprocess.html) of the [**future**](https://cran.r-project.org/package=future) package is _deprecated_ since **future** 1.20.0 (2020-11-03).  It will eventually become _defunct_ and removed.  The background for this can be found in <https://github.com/HenrikBengtsson/future/issues/420>.

Your **TSstudio** package relies on `multiprocess`, cf. <https://github.com/RamiKrispin/TSstudio/search?q=multiprocess>.

Please migrate your code to the platform-independent `plan(multisession)` or the Linux/macOS-specific `plan(multicore)`.  If you want to emulate what `multiprocess` does, you can do something like:

```r
  if (parallelly::supportsMulticore()) {
    oplan <- plan(multicore)
  } else {
    oplan <- plan(multisession)
  }
  on.exit(plan(oplan))
```

BTW, if you don't already do so, please make sure to undo any `plan()` you set in your code, as illustrated by the above example.  This is needed to guarantee that calling your code won't override settings that the user has set previously.  You can read about this in <https://future.futureverse.org/reference/plan.html#for-package-developers>.

Thank you,

Henrik
(maintainer of the **future** package)

**Comment by RamiKrispin** [comment]
Thanks @HenrikBengtsson for the reminder. Unfortunately, due to my employer's open-source policies, I am currently blocked from contributing to this project and sadly will have to retire it.

**Comment by HenrikBengtsson** [comment]
Alternatively to retiring this project, you could also tech out to the R community and all of someone wants to take over as it's new maintainer. This happened to many other R packages in the past and CRAN supports transfers.

**Comment by RamiKrispin** [comment]
Unfortunately, I am also restricted from merging PR, and yes, probably finding a new maintainer would be the best option to keep this project alive.

**Comment by HenrikBengtsson** [comment]
Hi, have you had any chance to think about an alternative package maintainer. I hate for your package to be removed from CRAN, because you are not allowed to submit an updated version yourself.

**Comment by HenrikBengtsson** [comment]
Friendly reminder; 'multiprocess' has been deprecated since 2020-10-30.

**Comment by HenrikBengtsson** [comment]
An update and a follow-up here: `future::multiprocess` has been deprecated since October 2020, and defunct since March 2023.  It will soon be removed from **future**.  When that happens, your package will break (see below).  If this doesn't get fixed, your package probably fall of CRAN at some point.

*   checking dependencies in R code ... WARNING
    ```
    Namespace in Imports field not imported from: ‘forecastHybrid’
      All declared Imports should be used.
    Missing or unexported object: ‘future::multiprocess’
    ```

**Comment by HenrikBengtsson** [comment]
Looks like you figured out a way for updating the package.
