### ISSUE TITLE
Plot Display Issue: Limited Time Range

### ISSUE THREAD

**Issue by sofia2027** [RamiKrispin/TSstudio#69]
![problem3](https://github.com/RamiKrispin/TSstudio/assets/117331146/c6dc5758-30a3-4219-9c90-150aefb83be5)
This the code I used : 

file_path <- "*****************/***********.xlsx"

data <- readxl::read_excel(file_path)

ts_data <- data[, c("Year", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")]

ts_object <- ts(cbind(ts_data[, -1]), start = c(ts_data$Year[1], 1), frequency = 12)

ts_plot(ts_object, 
        title = "Monthly TDS variations",
        Ytitle = "TDS (mg/l)")

ts_seasonal(ts_object, type = "all")
![problem1](https://github.com/RamiKrispin/TSstudio/assets/117331146/c5b8dbcc-d0e6-4914-b7b2-e5e300f8f011)
![problem2](https://github.com/RamiKrispin/TSstudio/assets/117331146/525d84ec-933f-4a4a-879d-2c320913fdde)

**Comment by RamiKrispin** [comment]
@sofia2027 potentially, the issue is with your data transformation to the `ts` object. Could you please try the following code and let me know if this works for you?

```r
library(TSstudio)
library(tidyr)
library(dplyr)
library(readxl)
data <- read_excel("~/Downloads/Grootdraai_Pivoted.xlsx")

d <- pivot_longer(data = data, cols = !Year, names_to = "month", values_to = "y") |>
  mutate(date = as.Date(paste(Year, month, "1", sep = " "), format("%Y %b %d")),
                month = lubridate::month(date))

head(d)

ts_obj = ts(data = d$y, start = c(d$Year[1], d$month[1]), frequency = 12)

ts_plot(ts_obj,
        title = "Monthly TDS variations",
        Ytitle = "TDS (mg/l)")

ts_seasonal(ts_obj, type = "all")
```

This is the output I am getting:
<img width="1009" alt="image" src="https://github.com/RamiKrispin/TSstudio/assets/12760966/88cd9cfd-5042-4fea-836d-ba0f1aa6efad">

**Comment by RamiKrispin** [comment]
Found the issue, the way your transforming the data into time series object creates a `mts` (multiple time series) object as opposed to a `ts` object:
```r
class(ts_object)
[1] "mts"    "ts"     "matrix"
```

**Comment by sofia2027** [comment]
Rami, thanks a bunch! Your help was fantastic, much appreciated!
