### ISSUE TITLE
Xreg to forecast 

### ISSUE THREAD

**Issue by davidjbrumfield** [RamiKrispin/TSstudio#7]
Hi Rami! Thanks for the cool package! 

When using ts_backtesting, you are able to pass xreg arguments to train the models, but there is no way to pass the xreg forecast counterparts to the forecast() call.

**Comment by RamiKrispin** [comment]
Hi @davidjbrumfield,

I pushed an updated to the develop version on github (will be available on CRAN on the next release). Add new argument xreg.h which represents the future value of the regressor that you are using (must be equal to the horizon of the forecast - the 'h' argument). Here is an example I create, regression the auto.arima, nnetar and the hybrid models with Fourier series:
`
devtools::install_github("RamiKrispin/TSstudio")
library(TSstudio)
data(USgas)

# Setting the forecast horizon
h <- 3 

# Setting fourier series as a regressor
x_reg <- forecast::fourier(USgas, K = 5)

# Setting the future values of the fourier series
# Must be at the same length as the forecast horizon
x_reg.h <- forecast::fourier(USgas, K = 5, h = h)

test <- ts_backtesting(ts.obj = USgas, 
                    models = "ahn", 
                    periods = 6,
                    h = h,
                    xreg.h = x_reg.h, 
                    a.arg = list(xreg = x_reg), 
                    h.arg = list(models = "aet", a.args = list(xreg = x_reg)), 
                    n.arg = list(xreg = x_reg))

`
Please let me know if this is working with your data.

Best,
Rami
