### ISSUE TITLE
ts_backtesting function not found

### ISSUE THREAD

**Issue by verajosemanuel** [RamiKrispin/TSstudio#8]
Tried some examples from vignette. All of them worked with the exception of  ts_backtesting. Tested on both CRAN and development version.
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

```
USgas_backtesting <- TSstudio::ts_backtesting(USgas, 
                                    models = "abehntw", 
                                    periods = 6, 
                                    error = "RMSE", 
                                    window_size = 12, 
                                    h = 12)

 'ts_backtesting' is not an exported object from 'namespace:TSstudio'
```

**Comment by RamiKrispin** [comment]
Can you try to remove the package from your machine, reset your R session and then reinstall it? It typically happened when installing a package that is already loaded in the current environment

**Comment by verajosemanuel** [comment]
That did the trick!

Thanks for an amazing package

**Comment by RamiKrispin** [comment]
Great, happy that it worked

**Comment by geegro05** [comment]
I'm having the same issue. I see that "train_model" is trying to do something similar, but it doesn't seem to allow Bayesian and NN forecasts. I tried the trick of removing TSstudio, restarting, and reinstalling, to the same error message - could not find function "ts_backtesting". Any help would be appreciated!

**Comment by mbecker0813** [comment]
I am also having this same issue. I have TSstudio 0.1.6 and tried removing, restarting, and reinstalling but it did not work.

**Comment by RamiKrispin** [comment]
Hi @geegro05, @mbecker0813 

The `ts_backtesting` was deprecated and on version 0.1.5 and defunct by the [train_model](https://ramikrispin.github.io/TSstudio/articles/forecasting.html#training-multiple-time-series-model-with-backtesting)  function, which provides the same functionality but more flexible. As many people contact me about the `ts_backtesting`, the plan is to return the function on the next release of the package.

Sadly, the Bayesian model (BSTS) was removed as its dependencies (Boom and BookSpikeSlab) cannot be installed on Docker container and therefore, prevent the TSstudio package from deployed on Docker images.

In the meanwhile, until the next update to CRAN, you can install version 0.1.5 from CRAN archive:
```
utils::install.packages("https://cran.r-project.org/src/contrib/Archive/TSstudio/TSstudio_0.1.5.tar.gz", repos=NULL, type = "source")
```
