### ISSUE TITLE
ts_seasonal type=boxplot ordering months wrong when not starting in January

### ISSUE THREAD

**Issue by verajosemanuel** [RamiKrispin/TSstudio#9]
My time series first month is August, so when plotting using ts_seasonal boxplot months are ordered in x-axis from august to July.

I think this does not make sense. Please allow ordering by natural year months (from January to December)

**Comment by RamiKrispin** [comment]
Can you please send me the `class`, `start` and `end` functions output for the series you are using?

**Comment by verajosemanuel** [comment]
> class(tm)
[1] "ts"

tm <- ts(monthly$summary,
                   frequency = 12,
                   start = c(2017,06)
                   end = c(2019,03)

**Comment by RamiKrispin** [comment]
Thanks, I pushed an [update](https://github.com/RamiKrispin/TSstudio/commit/814dbab814b818e0255beda4f99a350706a099cc#diff-df0926a13d3fc1435d47537de060d110) to the dev version and will be available on the CRAN version on the next release.
